name: "build latest"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-10.15, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: install webkit2gtk on Ubuntu runners
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: install npm dependencies
        run: yarn
      - name: install rust cli
        run: cargo install tauri-cli --git https://github.com/tauri-apps/tauri
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "rite v__VERSION__"
          releaseBody:
            "# rite v__VERSION__:\nSee the assets to download and install this version.


            Changes in this version:
            * Escape now closes the command palette. Finally.

            * Added focus mode, to reduce distractions even further.

            * Fixed longstanding issues with text overflow in command palette. Not perfect, but getting there.

            * Added table of contents generation via `toc` command.

            * Added in-app keybind viewer.


            Note that Windows users will need to have
            [WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)
            installed."
          releaseDraft: false
          prerelease: false
          tauriScript: "cargo tauri"
